title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: nighthawkcoders
baseurl: "/student"
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0 # better then cayman
#remote_theme: pages-themes/hacker@v0.2.0 # Hella good
#remote_theme: pages-themes/cayman@v0.2.0 # Decent
#remote_theme: pages-themes/time-machine@v0.2.0 Decent
plugins:
- jekyll-remote-theme
future: true
